SELECT LAST_NAME as Sobrenome,
	(SELECT JOB_TITLE FROM JOBS BOT WHERE SUP.JOB_ID = BOT.JOB_ID) as Cargo,
    PHONE_NUMBER as Telefone,
    (SELECT DEPARTMENT_NAME FROM DEPARTMENTS BOT WHERE SUP.DEPARTMENT_ID = BOT.DEPARTMENT_ID) as Departamento
FROM
	(SELECT LAST_NAME, JOB_ID, PHONE_NUMBER, DEPARTMENT_ID
	FROM EMPLOYEES SUP
    WHERE
		"Toronto" = (SELECT CITY FROM LOCATIONS WHERE LOCATION_ID = 
						(SELECT LOCATION_ID FROM DEPARTMENTS BOT WHERE SUP.DEPARTMENT_ID = BOT.DEPARTMENT_ID)
					)
	) SUP