SELECT LAST_NAME as Sobrenome_Empregado, PHONE_NUMBER as Telefone_Empregado,
	(SELECT LAST_NAME FROM EMPLOYEES BOT WHERE SUP.MANAGER_ID = BOT.EMPLOYEE_ID) as Sobrenome_Gerente,
    (SELECT PHONE_NUMBER FROM EMPLOYEES BOT WHERE SUP.MANAGER_ID = BOT.EMPLOYEE_ID) as Telefone_Gerente
FROM EMPLOYEES SUP
WHERE MANAGER_ID IS NOT NULL