SELECT FIRST_NAME as Emp_Name, HIRE_DATE as Emp_Hire_Date,
	(SELECT FIRST_NAME FROM EMPLOYEES BOT WHERE SUP.MANAGER_ID = BOT.EMPLOYEE_ID) as Mng_Name,
    (SELECT HIRE_DATE FROM EMPLOYEES BOT WHERE SUP.MANAGER_ID = BOT.EMPLOYEE_ID) as Mng_Hire_Date
FROM (SELECT * FROM EMPLOYEES SUP WHERE HIRE_DATE <
		(SELECT HIRE_DATE FROM EMPLOYEES BOT WHERE SUP.MANAGER_ID = BOT.EMPLOYEE_ID)) as SUP